### ISSUE TITLE
Panic in delete cluster in case of ACSK

### ISSUE THREAD

**Issue by colin014** [banzaicloud/pipeline#896] opened 2018-08-21 10:11 UTC
```time="2018-08-21T11:50:18+02:00" level=info msg="Start deleting cluster (alibaba)" function=DeleteCluster
time="2018-08-21T11:50:18+02:00" level=debug msg="Secret is nil.. load from vault" function=getSecret
time="2018-08-21T11:50:18+02:00" level=debug msg="Get secret: secret/data/orgs/1/0cecfc0a83b98c9ff58140d663b25c164192818f6630cb6541bc1abf7aa3adf6" function=Get
time="2018-08-21T11:50:20+02:00" level=info msg="Delete config secret" function=Delete
time="2018-08-21T11:50:20+02:00" level=info msg="Delete unused cluster secrets" cluster=74 function=preDelete organization=1
time="2018-08-21T11:50:20+02:00" level=debug msg="Searching for secrets [orgid: 1, query: &secret.ListSecretsQuery{Type:\"\", Tag:\"clusterUID:5dc64a6e-28aa-42d5-920e-c9b2d6691493\", Values:false}]" function=List
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1322 [running]:
github.com/banzaicloud/pipeline/secret.parseSecret(0xc42087a6c0, 0x40, 0xc42110e1e0, 0xc42110e100, 0x0, 0x0, 0x0)
	/Users/colin/go/src/github.com/banzaicloud/pipeline/secret/store.go:284 +0x7ae
github.com/banzaicloud/pipeline/secret.(*secretStore).List(0xc4200943e0, 0x1, 0xc4207be690, 0x1, 0x1, 0xc4202038c0, 0x2f, 0xc4210fc240)
	/Users/colin/go/src/github.com/banzaicloud/pipeline/secret/store.go:386 +0x3c1
github.com/banzaicloud/pipeline/secret.(*secretStore).DeleteByClusterUID(0xc4200943e0, 0x1, 0xc420b728d0, 0x24, 0xc420e7dde0, 0x3)
	/Users/colin/go/src/github.com/banzaicloud/pipeline/secret/store.go:160 +0x2e5
github.com/banzaicloud/pipeline/model.(*ClusterModel).preDelete(0xc420484c00)
	/Users/colin/go/src/github.com/banzaicloud/pipeline/model/cluster.go:267 +0x240
github.com/banzaicloud/pipeline/model.(*ClusterModel).Delete(0xc420484c00, 0x326e460, 0xc420e7df78)
	/Users/colin/go/src/github.com/banzaicloud/pipeline/model/cluster.go:276 +0xae
github.com/banzaicloud/pipeline/cluster.(*ACSKCluster).DeleteFromDatabase(0xc420300190, 0xc420a285e0, 0x18)
	/Users/colin/go/src/github.com/banzaicloud/pipeline/cluster/acsk.go:680 +0x2f
github.com/banzaicloud/pipeline/api.postDeleteCluster(0x3d43c20, 0xc420300190, 0x1, 0xc420b76171, 0x4)
	/Users/colin/go/src/github.com/banzaicloud/pipeline/api/cluster.go:568 +0x361
created by github.com/banzaicloud/pipeline/api.DeleteCluster
	/Users/colin/go/src/github.com/banzaicloud/pipeline/api/cluster.go:520 +0x178```

**Comment by baluchicken** [comment] 2018-08-21 12:26
Fixed by https://github.com/banzaicloud/pipeline/commit/029f2a78ce57a86dabe2fbdfbc5beab7d6729b1f

**Comment by baluchicken** [comment] 2018-08-23 12:50
Closing this because I cannot reproduce it, please reopen if necessary

**Closed by baluchicken** 2018-08-23 12:50 UTC
