### ISSUE TITLE
Persist user defined helm repositories 

### ISSUE THREAD

**Issue by sancyx** [banzaicloud/pipeline#2125] opened 2019-07-12 16:07 UTC
The goal is to able to persist helm repos, so that they are not lost in case of a pod restart plus users of the same organisation can see the same list of repositories.
The solution would be to create a RepositoryStore which will have two implementations: FileRepositoryStore & DBRepositoryStore. Repositories will be stored & fetched from db while repo index file and chart files will still be stored on local filesystem.

**Comment by sagikazarmark** [comment] 2019-09-10 10:10
Duplicate of #1069 ?

**Closed** 2020-02-28 15:05 UTC
Labels: component/helm, resolution/duplicate
